[project]
name = "whisperlive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyannote-audio>=3.4.0",
    "python-dotenv>=1.1.1",
    "speechbrain>=1.0.3",
    "transformers>=4.56.1",
]
